-- public.usuarios definition

-- Drop table

-- DROP TABLE public.usuarios;

CREATE TABLE public.usuarios (
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 "name" varchar NOT NULL,
                                 last_name varchar NOT NULL,
                                 email varchar NOT NULL,
                                 "password" varchar NOT NULL,
                                 birth_date date NOT NULL,
                                 active bool DEFAULT true NOT NULL,
                                 updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 CONSTRAINT usuarios_pk PRIMARY KEY (id)
);

